config/routes.rb
Rails.application.routes.draw do

  root controller: :rooms, action: :chat
  resources :room_messages
  resources :rooms
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/', to: 'video#home'
  # get '/login', to: 'video#login'
  get '/party', to: 'video#party'
  get '/screenshare', to: 'video#screenshare'
  
  post '/login', to: 'video#login'
  # post 'chat/send', to: 'video#chat'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/models/room_message.rb
class RoomMessage < ApplicationRecord
  belongs_to :room
  belongs_to :user
end

app/models/session.rb
require 'opentok'

class Session < ApplicationRecord
  # api_key = '47186494'
  # api_secret = '4cb875bc59cb6a18df44862b79ff3cfa3d7270db'
  @opentok = OpenTok::OpenTok.new ENV['OPENTOK_API_KEY'], ENV['OPENTOK_API_KEY_SECRET']
  
  # We want to do 2 things:
  def self.create_new_session
    session = @opentok.create_session :media_mode => :routed
    record = Session.new
    record.session_id = session.session_id
    record.save
    @session_id = session.session_id
    @session_id
  end
  # create a session or connect to one if it exists
  def self.create_or_load_session_id
    if Session.any?
      last_session = Session.last
      if last_session && last_session.expired == false
        @session_id = last_session.session_id
        @session_id
      elsif (last_session && last_session.expired == true) || !last_session
        session_id = create_new_session
      else
        raise 'Something went wrong with the session try again!'
      end
    else
      @session_id = create_new_session
    end
  end
  # Create a token for session and to be able to connect to session
    def self.create_token(username, moderator_name, session_id)
      @token = username == moderator_name ? @opentok.generate_token(session_id, { role: :moderator }) : @opentok.generate_token(session_id)
    end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  validates :username, uniqueness: true, presence: true
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_site_lang_options
    before_action :set_site_welcome_options
    before_action :set_welcome_form_options
    before_action :set_site_navbar_options
    before_action :set_site_chat_options
    CONFIG = YAML.load_file("#{Rails.root}/config/site_info.yml")
  
    def set_site_lang_options
      @lang = CONFIG['language']
      @lang_dir = CONFIG['lang_direction']
    end
  
    def set_site_welcome_options
      @welcome_message = CONFIG['landing_page']['welcome_message']['text']
    end
  
    def set_welcome_form_options
      @name_form_text = CONFIG['landing_page']['name_form']['text']
      @name_placeholder_text = CONFIG['landing_page']['name_form']['name_placeholder_text']
      @password_placeholder_text = CONFIG['landing_page']['name_form']['password_placeholder_text']
      @name_form_submit_button_text = CONFIG['landing_page']['name_form']['submit_button_text']
    end
  
    def set_site_navbar_options
      @navbar_title = CONFIG['navbar']['title']['text']
    end
  
    def set_site_chat_options
      @submit_button_text = CONFIG['text_chat']['submit_button_text']
      @chat_placeholder_text = CONFIG['text_chat']['placeholder_text']
    end
end

app/controllers/room_messages_controller.rb
class RoomMessagesController < ApplicationController
  belongs_to :user
  belongs_to :room, inverse_of: :room_messages
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  has_many :room_messages, dependent: :destroy, inverse_of: :room    
  def chat
    @rooms = Room.all
  end
end

app/controllers/video_controller.rb
require 'opentok'

class VideoController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_opentok_vars
  
  def set_opentok_vars
    @api_key = ENV['OPENTOK_API_KEY']
    @api_secret = ENV['OPENTOK_API_SECRET']
    @session_id = Session.create_or_load_session_id
    @token = Session.create_token(@name, @moderator, @session_id)
    @moderator_name = ENV['MODERATOR_NAME']
    @name ||= params[:name]
  end

  def home
  end

  def party
  end

  def screenshare
    @darkmode = 'dark'
  end

  def login
    @name = user_params[:name]
    if user_params[:password] == ENV['PARTY_PASSWORD']
      # raise
      redirect_to party_path(name: @name)
    else
      redirect_to('/', flash: { error: 'Incorrect password' })
    end
  end

  def chat
  end

  private

  def user_params
    params.permit(:name, :password, :authenticity_token, :commit)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/room_messages_helper.rb
module RoomMessagesHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/video_helper.rb
module VideoHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VideoWatchParty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
    <script>
      var api_key = '<%= @api_key %>'
      var api_secret = '<%= @api_secret %>'
      var session_id = '<%= @session_id %>'
    </script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="<%= @darkmode if @darkmode %>">
    <%= yield %>
    <%= render partial: 'footer' %>
  </body>
</html>

app/views/video/_button-chat.html.erb
<button class="btn-chat" id="showChat"><svg viewBox="0 0 512 512"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 496 496"><path fill="white" d="M392 279.499v-172c0-26.467-21.533-48-48-48H48c-26.467 0-48 21.533-48 48v172c0 26.467 21.533 48 48 48h43.085l.919 43.339c.275 13.021 15.227 20.281 25.628 12.438l73.983-55.776H344c26.467-.001 48-21.534 48-48.001zm-205.74 16a16.003 16.003 0 00-9.632 3.224l-53.294 40.179-.588-27.741c-.185-8.702-7.292-15.661-15.996-15.661H48c-8.822 0-16-7.178-16-16v-172c0-8.822 7.178-16 16-16h296c8.822 0 16 7.178 16 16v172c0 8.822-7.178 16-16 16H186.26zm309.74-88v132c0 26.468-21.532 48-48 48h-43.153l-.852 33.408c-.222 8.694-7.347 15.592-15.994 15.592-6.385 0-2.83 1.107-82.856-49H232c-8.837 0-16-7.163-16-16s7.163-16 16-16c84.866 0 80.901-.898 86.231 2.438l54.489 34.117.534-20.964c.222-8.675 7.317-15.592 15.995-15.592H448c8.822 0 16-7.178 16-16v-132c0-8.822-7.178-16-16-16-8.837 0-16-7.163-16-16s7.163-16 16-16c26.468.001 48 21.533 48 48.001zm-200-43c0 8.837-7.163 16-16 16H112c-8.837 0-16-7.163-16-16s7.163-16 16-16h168c8.837 0 16 7.163 16 16zm-29 70c0 8.837-7.163 16-16 16H141c-8.837 0-16-7.163-16-16s7.163-16 16-16h110c8.837 0 16 7.163 16 16z"/></svg></button>

app/views/video/_chat.html.erb
<div class="row">
  <div class="col-12 col-md-3">
    <div class="mb-3">
      <%= link_to new_room_path, class: "btn btn-primary" do %>
        Create a room
      <% end %>
    </div>

    <% if @rooms.present? %>
      <nav class="nav flex-column">
        <% @rooms.each do |room| %>
          <%= link_to room.name, room_path(room), class: "nav-link room-nav-link" %>
        <% end %>
      </nav>
    <% else %>
      <div class="text-muted">
        The are no rooms
      </div>
    <% end %>
  </div>

  <div class="col">
    <div class="alert alert-primary">
      <h4 class="alert-heading">
        Welcome to the RailsChatTutorial!
      </h4>

      <p>
        We need to talk.
      </p>

      <hr />

      <p>
        You can create or join a room from the sidebar.
      </p>
    </div>
</div>

app/views/video/_footer.html.erb
<div class="footer sticky-bottom">
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/video/_header.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <h1>Tokyo Watch Party!</h1>
    <i class="fas fa-tv"></i>
  <% end %>
    <p id="participant-count"></p>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <button id="watch-mode">Watch Mode On/Off</button>
        <%= link_to "Home", "#", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Messages", "#", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/video/home.html.erb
<%= render partial: 'header' %>
  <div class="container">
    <div class='landing'>
      <h1>Welcome to Tokyo Watch Party!</h1>
      <p>Enter the name and code to start partying</p>
        <%= form_with(url: '/login', method: 'post') do |f| %>
        <%= f.text_field 'name', placeholder: "please enter your name" %>
        <%= f.password_field 'password', placeholder: "enter the room password" %>
        <%= f.submit "Submit", style: "background-color: red;" %>
        <% flash.each do |type, msg| %>
          <p class="error"><%= "error" %></p>
        <% end %>
      <% end %>
    </div>
  </div>

app/views/video/login.html.erb
<h1>Video#login</h1>
<p>Find me in app/views/video/login.html.erb</p>

app/views/video/party.html.erb
<script type="text/javascript">
  const token = '<%= @token %>';
  const name = '<%= @name %>';
  const moderator_env_name = '<%= @moderator_name %>';
  (function() {
    if(window.localStorage) {
      if(!localStorage.getItem('firstLoad')) {
        localStorage['firstLoad'] = true;
        window.location.reload();
      }
    } else {
      localStorage.removeItem('firstLoad');
    }
  })();
</script>
<%= render partial: 'header' %>
<div class="container">
    <div class="videos">
      <div class="publisher" id="publisher"></div>
      <div class="subscriber" id="subscribers"></div>
    </div>

    <aside class="chat">
      <%= render partial: 'chat' %>
    </aside>

    <%= render partial: 'button-chat' %>
</div>

app/views/video/screenshare.html.erb
<script type="text/javascript">
  const token = '<%= @token %>';
  const name = '<%= @name %>';
  const moderator_env_name = '<%= @moderator_name %>';
  (function() {
    if(window.localStorage) {
      if(!localStorage.getItem('screenshareFirstLoad')) {
        localStorage['screenshareFirstLoad'] = true;
        window.location.reload();
      }
    } else {
      localStorage.removeItem('screenshareFirstLoad');
    }
  })();
</script>

<header>
  <%= render partial: 'header' %>
</header>

<main class='app'>
  <div class="videos">
    <div class="screenshare" id="screenshare"></div>
    <div class="audio" id=""></div>
  </div>

  <aside class="chat">
    <%= render partial: 'chat' %>
  </aside>

  <%= render partial: 'button-chat' %>
</main>